# Copyright 2026 Esteban Román Catafau and Torbjörn E. M. Nordling
# SPDX-License-Identifier: Apache-2.0
"""Meta-tests: the CLI test suite exercises the complete argparse surface.

These tests introspect the parser built by :func:`cibica.cli._build_parser`
and statically scan every ``cli.main([...])`` invocation in ``tests/`` so
that adding a new subcommand, option, or flag without a test fails the suite.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

from cibica import cli

TESTS_DIR = Path(__file__).resolve().parent

# Auto-generated by argparse on every parser; nothing to exercise.
_EXEMPT_OPTIONS = frozenset({"-h", "--help"})


def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    raise AssertionError("CLI parser has no subcommands")


def _cli_surface() -> tuple[set[str], set[frozenset[str]]]:
    """All subcommand names and one alias-set per distinct option/flag.

    An option is considered covered when any of its aliases (e.g. ``-o`` or
    ``--output``) is used; identical alias-sets shared by several subcommands
    (the ``_add_common`` options) collapse into one requirement.
    """
    parser = cli._build_parser()
    subs = _subparsers_action(parser)
    parsers = [parser, *subs.choices.values()]
    alias_sets = set()
    for p in parsers:
        for action in p._actions:
            aliases = frozenset(action.option_strings) - _EXEMPT_OPTIONS
            if aliases:
                alias_sets.add(aliases)
    return set(subs.choices), alias_sets


def _used_in_tests() -> tuple[set[str], set[str]]:
    """Subcommands and option strings passed to ``cli.main([...])`` in tests/.

    Only string literals are collected: a computed argument (e.g.
    ``str(img)``) can never be a subcommand name or an option string here.
    """
    subcommands: set[str] = set()
    options: set[str] = set()
    for path in TESTS_DIR.glob("test_*.py"):
        for node in ast.walk(ast.parse(path.read_text())):
            if not (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "main"
                and node.args
                and isinstance(node.args[0], (ast.List, ast.Tuple))
            ):
                continue
            elts = node.args[0].elts
            literals = [
                e.value
                for e in elts
                if isinstance(e, ast.Constant) and isinstance(e.value, str)
            ]
            options.update(t.split("=")[0] for t in literals if t.startswith("-"))
            first = elts[0] if elts else None
            if (
                isinstance(first, ast.Constant)
                and isinstance(first.value, str)
                and not first.value.startswith("-")
            ):
                subcommands.add(first.value)
    return subcommands, options


def test_every_cli_subcommand_exercised():
    surface_subcommands, _ = _cli_surface()
    used_subcommands, _ = _used_in_tests()
    missing = surface_subcommands - used_subcommands
    assert not missing, (
        f"CLI subcommands never invoked via cli.main([...]) in tests/: "
        f"{sorted(missing)}"
    )


def test_every_cli_option_exercised():
    _, alias_sets = _cli_surface()
    _, used_options = _used_in_tests()
    missing = [sorted(aliases) for aliases in alias_sets if not aliases & used_options]
    assert not missing, (
        f"CLI options/flags never passed to cli.main([...]) in tests/: "
        f"{sorted(missing)}"
    )
